confluentPlatformImage: &cpImage
  image:
    tag: 5.4.0.0

global:
  initContainer:
    <<: *cpImage
  provider:
    registry:
      fqdn: docker.io
    name: gcp
    storage:
      provisioner: kubernetes.io/gce-pd
      reclaimPolicy: Delete
      parameters:
        type: pd-ssd
    sasl:
      plain:
        username=test
        password=test123

operator:
  name: operator
  image:
    tag: 0.275.0

zookeeper:
  <<: *cpImage
  resources:
    cpu: 200m
    memory: 512Mi

kafka:
  <<: *cpImage
  resources:
    cpu: 200m
    memory: 1Gi
  loadBalancer:
    enabled: false
  tls:
    enabled: false
  metricReporter:
    enabled: true
  configOverrides:
    server:
      - "auto.create.topics.enabled=true"

schemaregistry:
  <<: *cpImage
  dependencies:
    kafka:
      bootstrapEndpoint: kafka:9071

connect:
  image:
    repository: gamussa/kafka-connect-twitter
    tag: 5.4.0.0.3.33
  tls:
    enabled: false
  loadBalancer:
    enabled: false
  dependencies:
    kafka:
      brokerCount: 3
      bootstrapEndpoint: kafka:9071
    schemaregistry:
      enabled: true
      url: http://schemaregistry:8081

ksql:
  name: ksql
  replicas: 1
  tls:
    enabled: false
    fullchain: |-
    privkey: |-
    cacerts: |-
  loadBalancer:
    enabled: false
    domain: ""
  dependencies:
    kafka:
      brokerCount: 3
      brokerEndpoints: kafka:9071
      bootstrapEndpoint: kafka:9071

controlcenter:
  <<: *cpImage
  dependencies:
    c3KafkaCluster:
      zookeeper:
        endpoint: zookeeper:2181
      bootstrapEndpoint: kafka:9071
      brokerCount: 1
    connectCluster:
      enabled: true
      url: http://connectors:8083
    schemaRegistry:
      enabled: true
      url: http://schemaregistry:8081
    ksql:
      enabled: true
      url: http://ksql:8088
      

