# A note about JMX:
#
# * If you want to be able to access JMX from within the Docker network: 
#     -> Set JMX_HOSTNAME to the container's hostname and no need to expose the port 
# * If you want to be able to access JMX from your host machine
#     -> Set JMX_HOSTNAME to "localhost" and expose the JMX_PORT
#
# See also https://rmoff.net/2018/09/19/exploring-jmx-with-jmxterm/
---
version: '2'
services:
  zookeeper:
    image: 368821881613.dkr.ecr.us-west-2.amazonaws.com/confluentinc/cp-zookeeper:5.2.x-latest
    ports:
      - '31000:31000'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_JMX_HOSTNAME: "localhost"
      KAFKA_JMX_PORT: 31000

  kafka:
    # "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
    # An important note about accessing Kafka from clients on other machines: 
    # -----------------------------------------------------------------------
    #
    # The config used here exposes port 9092 for _external_ connections to the broker
    # i.e. those from _outside_ the docker network. This could be from the host machine
    # running docker, or maybe further afield if you've got a more complicated setup. 
    # If the latter is true, you will need to change the value 'localhost' in 
    # KAFKA_ADVERTISED_LISTENERS to one that is resolvable to the docker host from those 
    # remote clients
    #
    # For connections _internal_ to the docker network, such as from other services
    # and components, use kafka:29092.
    #
    # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
    # "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
    #  
    image: 368821881613.dkr.ecr.us-west-2.amazonaws.com/confluentinc/cp-enterprise-kafka:5.2.x-latest
    ports:
      - '9092:9092'
      - '31001:31001'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      KAFKA_JMX_HOSTNAME: "localhost"
      KAFKA_JMX_PORT: 31001

  schema-registry:
    image: 368821881613.dkr.ecr.us-west-2.amazonaws.com/confluentinc/cp-schema-registry:5.2.x-latest
    depends_on:
      - zookeeper
      - kafka
    ports:
      - '8081:8081'
      - '31002:31002'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_JMX_HOSTNAME: "localhost"
      SCHEMA_REGISTRY_JMX_PORT: 31002

  ksql-server:
    image: 368821881613.dkr.ecr.us-west-2.amazonaws.com/confluentinc/cp-ksql-server:5.2.x-156
    depends_on:
      - kafka
      - schema-registry
    ports:
      - '31003:31003'
    environment:
      KSQL_BOOTSTRAP_SERVERS: kafka:29092
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KSQL_KSQL_SERVICE_ID: asgard
      KSQL_JMX_HOSTNAME: "localhost"
      KSQL_JMX_PORT: 31003
      KSQL_LOG4J_ROOT_LOGLEVEL: "INFO"
      KSQL_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
      # --- Processing log config ---
      KSQL_LOG4J_PROCESSING_LOG_BROKERLIST: kafka:29092
      KSQL_LOG4J_PROCESSING_LOG_TOPIC: asgard_processing_log
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_NAME: asgard_processing_log
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"

  ksql-cli:
    image: 368821881613.dkr.ecr.us-west-2.amazonaws.com/confluentinc/cp-ksql-cli:5.2.x-latest
    depends_on:
      - ksql-server
    entrypoint: /bin/sh
    tty: true

  kafka-connect:
    image: 368821881613.dkr.ecr.us-west-2.amazonaws.com/confluentinc/cp-kafka-connect:5.2.x-latest
    # image: confluentinc/cp-kafka-connect:5.1.2
    ports:
      - '8083:8083'
      - '31004:31004'
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:29092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
      KAFKA_JMX_HOSTNAME: "localhost"
      KAFKA_JMX_PORT: 31004
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    command: 
      - bash 
      - -c 
      - |
        confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:0.1.1
        confluent-hub install --no-prompt jcustenborder/kafka-connect-twitter:0.2.32
        /etc/confluent/docker/run &
        echo "Waiting for Kafka Connect to start listening on kafka-connect ⏳"
        while [ $$(curl -s -o /dev/null -w %{http_code} http://kafka-connect:8083/connectors) -eq 000 ] ; do 
          echo -e $$(date) " Kafka Connect listener HTTP state: " $$(curl -s -o /dev/null -w %{http_code} http://kafka-connect:8083/connectors) " (waiting for 200)"
          sleep 5 
        done
        nc -vz kafka-connect 8083
        echo -e "\n--\n+> Creating Connector"
        curl -X POST http://kafka-connect:8083/connectors -H "Content-Type: application/json" -d '
        {
          "name": "datagen-pageviews",
          "config": {
            "connector.class": "io.confluent.kafka.connect.datagen.DatagenConnector",
            "kafka.topic": "pageviews",
            "quickstart": "pageviews",
            "max.interval": 100,
            "iterations": 10000000,
            "tasks.max": "1"
          }
        }
        '
        sleep infinity

  # rest-proxy:
  #   image: 368821881613.dkr.ecr.us-west-2.amazonaws.com/confluentinc/cp-kafka-rest:5.2.x-latest
  #   depends_on:
  #     - zookeeper
  #     - kafka
  #     - schema-registry
  #   ports:
  #     - '8082:8082'
  #     - '31005:31005'
  #   environment:
  #     KAFKA_REST_HOST_NAME: rest-proxy
  #     KAFKA_REST_BOOTSTRAP_SERVERS: 'kafka:29092'
  #     KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
  #     KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
  #     KAFKAREST_JMX_HOSTNAME: "localhost"
  #     KAFKAREST_JMX_PORT: 31005

  ksql-datagen-pageviews:
    image: 368821881613.dkr.ecr.us-west-2.amazonaws.com/confluentinc/ksql-examples:5.2.x-latest
    depends_on: 
      - ksql-server
      - schema-registry
    command: 
      - bash 
      - -c 
      - |
        echo "Waiting for KSQL to start listening  ⏳"
        while [ $$(curl -s -o /dev/null -w %{http_code} http://ksql-server:8088) -eq 000 ] ; do 
          echo -e $$(date) " KSQL Server listener HTTP state: " $$(curl -s -o /dev/null -w %{http_code} http://ksql-server:8088) " (waiting for 200)"
          sleep 5 
        done
        cub sr-ready schema-registry 8081 20 
        ksql-datagen \
        bootstrap-server=kafka:29092 \
        quickstart=pageviews \
        format=avro \
        topic=pageviews \
        schemaRegistryUrl=http://schema-registry:8081 \
        maxInterval=500

  ksql-datagen-users:
    image: 368821881613.dkr.ecr.us-west-2.amazonaws.com/confluentinc/ksql-examples:5.2.x-latest
    depends_on: 
      - ksql-server
      - schema-registry
    command: 
      - bash 
      - -c 
      - |
        echo "Waiting for KSQL to start listening  ⏳"
        while [ $$(curl -s -o /dev/null -w %{http_code} http://ksql-server:8088) -eq 000 ] ; do 
          echo -e $$(date) " KSQL Server listener HTTP state: " $$(curl -s -o /dev/null -w %{http_code} http://ksql-server:8088) " (waiting for 200)"
          sleep 5 
        done
        cub sr-ready schema-registry 8081 20 
        ksql-datagen \
        bootstrap-server=kafka:29092 \
        quickstart=users \
        format=avro \
        schemaRegistryUrl=http://schema-registry:8081
        topic=users \
        maxInterval=500
